-- Stop old deployed workers before applying. Never use CASCADE.
-- Preserve profiles, auth schemas, dhan_instruments, nse_universe,
-- market_universe and its nse_eod_market_caps dependency.
BEGIN;
DROP TABLE IF EXISTS
  public.screener_bulk_run_items,
  public.screener_bulk_runs,
  public.screener_company_snapshots,
  public.chart_refresh_log,
  public.chart_candles,
  public.quarterly_results,
  public.screener_fetch_runs,
  public.screener_fetch_queue,
  public.annual_fundamentals,
  public.annual_ratios,
  public.annual_balance_sheet,
  public.annual_cash_flows,
  public.shareholding_pattern,
  public.scheduler_log,
  public.god_logs,
  public.agent_state,
  public.nse_events,
  public.nse_board_meetings,
  public.nse_bm_runs,
  public.kite_holdings,
  public.kite_accounts,
  public.dhan_daily_candle_series,
  public.dhan_daily_candles,
  public.dhan_live_today,
  public.dhan_auth_state,
  public.watchlists,
  public.financials,
  public.results,
  public.stocks;
COMMIT;
